proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

frontend:
  build: images/frontend
  ports:
    - "8080:8080"
  volumes:
    - "sites/frontend/:/etc/nginx/sites-enabled/"
    - "www/frontend/:/var/www/"
  environment:
    VIRTUAL_HOST: frontend.test.com

api:
  build: images/api
  ports:
    - "8008:8008"
  links:
    - mysql:mysql
    - mongodb:mongodb
    - memcached:memcached
    - redis:redis
    - elasticsearch:elasticsearch
    - rabbitmq:rabbitmq
  volumes:
    - "sites/api/:/etc/nginx/sites-enabled/"
    - "www/api/:/var/www/"
  volumes_from:
    - apidata
  environment:
    VIRTUAL_HOST: api.test.com

admin:
  build: images/admin
  ports:
    - "5000:5000"
  volumes:
    - "www/admin/:/var/www/"
    - "sites/admin/:/etc/nginx/sites-enabled/"
  environment:
    VIRTUAL_HOST: admin.test.com

apidata:
  image: busybox
  volumes:
    - "/var/api/cache"
    - "/var/api/logs"

mysql:
  image: tutum/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_PASS: password
    ON_CREATE_DB: "apidb"

mongodb:
  image: tutum/mongodb
  ports:
    - "27017:27017"
    - "28017:28017"
  environment:
    MONGODB_PASS: password

rabbitmq:
  image: tutum/rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    RABBITMQ_PASS: password

memcached:
  image: tutum/memcached
  ports:
    - "11211:11211"
  environment:
    MEMCACHED_PASS: password

redis:
  image: tutum/redis
  ports:
    - "6379:6379"
  environment:
    REDIS_PASS: password

elasticsearch:
  image: tutum/elasticsearch
  ports:
    - "9200:9200"
  environment:
    ELASTICSEARCH_USER: admin
    ELASTICSEARCH_PASS: password